stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V
  - python3 -m venv venv
  - source venv/bin/activate

test:
  script:
  - pip install pytest==5.* pytest-flake8
  - pytest . --flake8 -v
