stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install pipfile-requirements
  - pipfile2req --dev Pipfile.lock > requirements.txt
  - pip install -r requirements.txt
  - python setup.py install

test:
  stage: test
  only:
    - master
  script:
    - pytest . -v
    - pytest . --flake8 -v
    - pytest . --cov=backboneql
