# Project information
site_name: duckQL
site_description: 'Python bindings for duckQL'
site_author: 'Jakub Dubec'
site_url: 'https://sibyx.github.io/duckql-python/'

# Navigation
nav:
  - Home: index.md
  - Properties:
      - 'Property': properties/property.md
      - 'Constant': properties/constant.md
      - 'Array': properties/array.md
      - 'Boolean': properties/boolean.md
      - 'Null': properties/null.md
  - Structures:
      - 'Between': structures/between.md
      - 'Comparision': structures/comparision.md
      - 'Distinct': structures/distinct.md
      - 'Interval': structures/interval.md
      - 'Join': structures/join.md
      - 'Limit': structures/limit.md
      - 'Operator': structures/operator.md
      - 'Order': structures/order.md
      - 'CastOperator': structures/cast_operator.md
      - 'Query': structures/query.md
  - Functions:
      - 'Avg': functions/avg.md
      - 'StringAgg': functions/string_agg.md
      - 'Concat': functions/concat.md
      - 'ConvertTimezone': functions/convert_timezone.md
      - 'Count': functions/count.md
      - 'CurrentDate': functions/current_date.md
      - 'DateAdd': functions/date_add.md
      - 'DateFormat': functions/date_format.md
      - 'DateSub': functions/date_sub.md
      - 'Extract': functions/extract.md
      - 'GroupConcat': functions/group_concat.md
      - 'Max': functions/max.md
      - 'Min': functions/min.md
      - 'Sum': functions/sum.md
      - 'Weekday': functions/weekday.md

# Repository
repo_name: 'Sibyx/duckql-python'
repo_url: 'https://github.com/Sibyx/duckql-python'

# Configuration
theme:
  name: 'material'
  language: 'en'

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
