[tool.poetry]
name = "duckql-python"
version = "0.6.1"
description = "JSON declarative SQL conversion library"
authors = ["Jakub Dubec <jakub.dubec@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
pydantic = "^1.0"
typing-extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.8.1"
mkdocs-material = "^5.0.1"
pytest = "^5.4.1"
coverage = "^5.0.4"
pytest-flake8 = "^1.0.4"
mkdocs = "^1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
